---
# {{ metas -}}
# https://docs.github.com/en/actions/reference
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners
name : release
on :
  push :
    tags :
    - "v[0-9]+.[0-9]+.[0-9]+-[0-9A-Za-z]+"
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs :
  default :
    runs-on : ubuntu-latest
    steps :
    - name : checkout
      uses : "actions/checkout@v2"
    - name : go setup
      uses : "actions/setup-go@v2"
      with : { go-version : "1.15" }
    - id : gpg
      name : gpg imports
      uses : "crazy-max/ghaction-import-gpg@v2"
      env :
        GPG_PRIVATE_KEY : "${{ secrets.GPG_PRIVATE_KEY }}"
        PASSPHRASE : "${{ secrets.GPG_PASSPHRASE }}"
    - name : go releaser
      uses : "goreleaser/goreleaser-action@v2"
      env :
        GPG_FINGERPRINT : "${{ steps.gpg.outputs.fingerprint }}"
        GITHUB_TOKEN : "${{ secrets.GITHUB_TOKEN }}"
      with :
        args : "release --rm-dist"
        version : "latest"
