---
# {{ metas -}}
# project_name : "default"

# before #
before :
  hooks :
  - "go mod tidy"

# build #
builds :
  #####
- skip : false
  id : "default"
  mod_timestamp : "{{ .CommitTimestamp }}"
  binary : "{{ .ProjectName }}_v{{ .Version }}"
  #####
  env : [ "CGO_ENABLED=0" ]
  ldflags : [ "-X main.version={{ .Version }} -X main.commit={{ .Commit }} -w -s" ]
  flags : [ "-trimpath" ]
  #####
  goarch : [ "amd64" , "386" , "arm64" , "arm" ]
  goos : [ "darwin" , "freebsd" , "linux" , "windows" ]
  ignore :
  - { goarch : "arm64" , goos : "darwin" }
  - { goarch : "arm" , goos : "darwin" }
  - { goarch : "arm64" , goos : "freebsd" }
  - { goarch : "arm" , goos : "freebsd" }
  - { goarch : "arm64" , goos : "windows" }
  - { goarch : "arm" , goos : "windows" }
  #####
  dir : "."
  main : "."

# archive #
archives :
- id : "default"
  name_template : "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  builds : [ "default" ]
  wrap_in_directory : false
  format : "zip"

# checksum #
checksum :
  disable : false
  name_template : "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm : "sha256"

# signs #
signs :
- id : "default"
  artifacts : "checksum"
  cmd : "gpg"
  args :
  - "--batch"
  - "--local-user"
  - "{{ .Env.GPG_FINGERPRINT }}"
  - "--output"
  - "${signature}"
  - "--detach-sign"
  - "${artifact}"

# release #
release :
  disable : false
  draft : false
changelog :
  skip : true
